spring.application.name=dmitryefremov-site
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/dmitryefremov
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
