-- Flyway Migration: V20261009115824162__seed_initial_data.sql
-- Description: Seed initial content for articles, podcast episodes, timecodes, and publication schedule.

-- Create podcast_episodes table if not already existing
CREATE TABLE IF NOT EXISTS podcast_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    thesis TEXT,
    description TEXT,
    audio_url VARCHAR(1024),
    media_link VARCHAR(1024),
    duration_seconds INT,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create podcast_timecodes table if not already existing
CREATE TABLE IF NOT EXISTS podcast_timecodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id BIGINT NOT NULL,
    time_offset_seconds INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_podcast_timecodes_episode FOREIGN KEY (episode_id) REFERENCES podcast_episodes (id) ON DELETE CASCADE
);

-- Create articles table if not already existing
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create publication schedule table if not already existing
CREATE TABLE IF NOT EXISTS publication_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed Articles
INSERT INTO articles (slug, title, summary, content, published_at)
VALUES
    (
        'systems-logic',
        'Deontic Logic in Autonomous Systems',
        'An exploration of deontic logic principles and application in software architectures.',
        '# Deontic Logic in Autonomous Systems\n\nSystems engineering requires formal guarantees for normative states (obligations, permissions, prohibitions).',
        '2026-01-15 10:00:00+00'
    ),
    (
        'theory-of-constraints',
        'Theory of Constraints in Software Engineering',
        'Applying Eliyahu Goldratt theory to bottleneck identification in distributed systems.',
        '# Theory of Constraints in Distributed Systems\n\nIdentifying and exploiting system bottlenecks is fundamental to throughput optimization.',
        '2026-02-10 14:00:00+00'
    ),
    (
        'autonomous-processes',
        'Autonomous Processes and Architectural Invariants',
        'Designing self-healing software components with strict invariants and zero drift.',
        '# Autonomous Processes and Architectural Invariants\n\nWhen systems operate without human intervention, explicit state boundaries ensure zero state corruption.',
        '2026-03-01 09:00:00+00'
    );

-- Seed Podcast Episodes
INSERT INTO podcast_episodes (slug, title, thesis, description, audio_url, media_link, duration_seconds, published_at)
VALUES
    (
        'ep-01-systems-reality',
        'Системы и реальность: Выпуск 1 — Введение в деонтическую логику',
        'Обсуждение системного мышления, деонтической логики и теории ограничений.',
        'Первый выпуск авторского подкаста «Системы и реальность».',
        'https://dmitryefremov.com/podcasts/ep-01.mp3',
        'https://youtube.com/watch?v=ep1',
        3600,
        '2026-02-01 12:00:00+00'
    ),
    (
        'ep-02-autonomous-processes',
        'Системы и реальность: Выпуск 2 — Автономные процессы',
        'Обсуждение автономии систем, конечных автоматов и логирования.',
        'Второй выпуск про инварианты и самовосстанавливающиеся процессы.',
        'https://dmitryefremov.com/podcasts/ep-02.mp3',
        'https://youtube.com/watch?v=ep2',
        2700,
        '2026-03-15 12:00:00+00'
    );

-- Seed Podcast Timecodes for Episode 1
INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 0, 'Введение и манифест', 'Вводная часть о системах и коде', 1
FROM podcast_episodes WHERE slug = 'ep-01-systems-reality';

INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 600, 'Теория ограничений', 'Анализ узких мест в архитектуре', 2
FROM podcast_episodes WHERE slug = 'ep-01-systems-reality';

INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 1800, 'Деонтическая логика', 'Формализация нормативных состояний', 3
FROM podcast_episodes WHERE slug = 'ep-01-systems-reality';

-- Seed Podcast Timecodes for Episode 2
INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 0, 'Приветствие и тема', 'Обзор второго выпуска', 1
FROM podcast_episodes WHERE slug = 'ep-02-autonomous-processes';

INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 450, 'Архитекторские инварианты', 'Плотные границы абстракций', 2
FROM podcast_episodes WHERE slug = 'ep-02-autonomous-processes';

INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 1500, 'Заключение и итоги', 'Практические советы', 3
FROM podcast_episodes WHERE slug = 'ep-02-autonomous-processes';

-- Seed Publication Schedule Items
INSERT INTO publication_schedule (topic, platform, status, scheduled_at)
VALUES
    (
        'Деонтическая логика и нормы в коде',
        'TELEGRAM',
        'PUBLISHED',
        '2026-01-10 12:00:00+00'
    ),
    (
        'Системы и реальность: Выпуск 2',
        'YOUTUBE',
        'IN_PRODUCTION',
        '2026-03-20 15:00:00+00'
    ),
    (
        'Теория ограничений в архитектуре',
        'ARTICLE',
        'SCHEDULED',
        '2026-04-01 10:00:00+00'
    );
