-- Seed realistic initial data for podcast episodes, articles, and publication schedule

-- 1. Create publication_schedules table if not exists (for publication schedule features)
CREATE TABLE IF NOT EXISTS publication_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    topic_summary TEXT,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_publication_schedules_platform ON publication_schedules(platform);
CREATE INDEX IF NOT EXISTS idx_publication_schedules_status ON publication_schedules(status);

-- 2. Seed Publication Schedules
INSERT INTO publication_schedules (title, platform, status, topic_summary, scheduled_at)
SELECT
    'Инварианты в распределенных системах',
    'TELEGRAM',
    'PUBLISHED',
    'Разбор критических секций, поглощающих состояний и атомарности в Telegram @efremov_mvp',
    TIMESTAMP WITH TIME ZONE '2026-10-01 12:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM publication_schedules WHERE title = 'Инварианты в распределенных системах'
);

INSERT INTO publication_schedules (title, platform, status, topic_summary, scheduled_at)
SELECT
    'Системы и реальность #2',
    'YOUTUBE',
    'PUBLISHED',
    'Выпуск подкаста о восстанавливаемости и транзакционных последовательностях на YouTube @efremov_dmitriy',
    TIMESTAMP WITH TIME ZONE '2026-10-03 15:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM publication_schedules WHERE title = 'Системы и реальность #2'
);

INSERT INTO publication_schedules (title, platform, status, topic_summary, scheduled_at)
SELECT
    'Теория ограничений в инжиниринге ПО',
    'ARTICLE',
    'IN_PRODUCTION',
    'Лонгрид о 5 шагах фокусировки TOC и устранении узких мест в архитектуре',
    TIMESTAMP WITH TIME ZONE '2026-10-12 10:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM publication_schedules WHERE title = 'Теория ограничений в инжиниринге ПО'
);

INSERT INTO publication_schedules (title, platform, status, topic_summary, scheduled_at)
SELECT
    'Деонтическая логика в микросервисах',
    'TELEGRAM',
    'SCHEDULED',
    'Заметка про модальные операторы нормативных систем в Telegram @efremov_mvp',
    TIMESTAMP WITH TIME ZONE '2026-10-15 18:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM publication_schedules WHERE title = 'Деонтическая логика в микросервисах'
);

-- 3. Seed Articles
INSERT INTO articles (slug, title, summary, content, published_at)
SELECT
    'deontic-logic-autonomous-systems',
    'Деонтическая логика и нормативные регуляторы в автономных системах',
    'Исследование формального синтаксиса нормативных систем: как обязательства, запреты и разрешения кодируются в архитектуре программных агентов.',
    '# Деонтическая логика и нормативные регуляторы в автономных системах

## Введение

Ваш код и ваши решения — это то, кто вы есть на самом деле. В современных распределенных и автономных системах концепция безопасности и предсказуемости опирается на строгие математические и логические модели.

$$
O(p) \implies \neg P(\neg p)
$$

### Нормативные операторы
1. **O (Obligatory)** — действие обязательно для выполнения.
2. **P (Permitted)** — действие разрешено.
3. **F (Forbidden)** — действие запрещено.

Деонтическая логика позволяет формализовать инварианты на уровне архитектуры, устраняя неопределенность при параллельном исполнении.',
    TIMESTAMP WITH TIME ZONE '2026-10-01 10:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM articles WHERE slug = 'deontic-logic-autonomous-systems'
);

INSERT INTO articles (slug, title, summary, content, published_at)
SELECT
    'theory-of-constraints-engineering',
    'Теория ограничений Голдратта в инжиниринге ПО',
    'Практическое применение TOC для поиска узких мест в масштабируемых микросервисных архитектурах и пропускной способности команд.',
    '# Теория ограничений Голдратта в инжиниринге ПО

Любая система имеет ровно одно главное ограничение в каждый момент времени. Попытка оптимизировать компоненты вне узкого места ведет лишь к накапливанию незавершенной работы.

```
[Входной поток] -> [Сервис А (100 rps)] -> [Сервис Б (20 rps)] -> [Выход]
                                                   ^
                                            (Узкое место)
```

### 5 шагов фокусировки TOC:
1. Выявить ограничение системы.
2. Решить, как максимально использовать ограничение.
3. Подчинить всё остальное этому решение.
4. Расшить ограничение.
5. Не допустить инерции — вернуться к шагу 1.',
    TIMESTAMP WITH TIME ZONE '2026-10-05 14:30:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM articles WHERE slug = 'theory-of-constraints-engineering'
);

-- 4. Seed Podcast Episodes
INSERT INTO podcast_episodes (slug, title, thesis, description, audio_url, media_link, duration_seconds, published_at)
SELECT
    'systems-and-reality-ep1',
    'Системы и реальность #1: Архитектура чистого разума',
    'Фундаментальный разбор взаимосвязи абстрактных системных моделей и физических ограничений высоконагруженных платформ.',
    'В первом выпуске подкаста «Системы и реальность» Дмитрий Ефремов разбирает инварианты надежности, деонтическую логику в коде и способы проектирования устойчивых систем.',
    'https://dmitryefremov.com/media/podcast/ep1.mp3',
    'https://youtube.com/@efremov_dmitriy/videos/ep1',
    2700,
    TIMESTAMP WITH TIME ZONE '2026-09-20 12:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM podcast_episodes WHERE slug = 'systems-and-reality-ep1'
);

INSERT INTO podcast_episodes (slug, title, thesis, description, audio_url, media_link, duration_seconds, published_at)
SELECT
    'systems-and-reality-ep2',
    'Системы и реальность #2: Инварианты и восстанавливаемость',
    'Как строить транзакционные последовательности с гарантией отсутствия потерянных состояний и неопределенности.',
    'Во втором выпуске обсуждаем доказательную инженерию, идемпотентность API и реакцию систем на внешние сбои.',
    'https://dmitryefremov.com/media/podcast/ep2.mp3',
    'https://youtube.com/@efremov_dmitriy/videos/ep2',
    3150,
    TIMESTAMP WITH TIME ZONE '2026-09-27 12:00:00+00'
WHERE NOT EXISTS (
    SELECT 1 FROM podcast_episodes WHERE slug = 'systems-and-reality-ep2'
);

-- 5. Seed Timecodes for Ep 1
INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT
    e.id,
    0,
    'Введение и манифест',
    'Приветствие и основные тезисы выпуска',
    1
FROM podcast_episodes e
WHERE e.slug = 'systems-and-reality-ep1'
  AND NOT EXISTS (
      SELECT 1 FROM podcast_timecodes t WHERE t.episode_id = e.id AND t.time_offset_seconds = 0
  );

INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT
    e.id,
    600,
    'Формальные модели и деонтика',
    'Как логика правил определяет границы систем',
    2
FROM podcast_episodes e
WHERE e.slug = 'systems-and-reality-ep1'
  AND NOT EXISTS (
      SELECT 1 FROM podcast_timecodes t WHERE t.episode_id = e.id AND t.time_offset_seconds = 600
  );

INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT
    e.id,
    1800,
    'Атомарность и критические секции',
    'Практика защиты данных от состояния гонки',
    3
FROM podcast_episodes e
WHERE e.slug = 'systems-and-reality-ep1'
  AND NOT EXISTS (
      SELECT 1 FROM podcast_timecodes t WHERE t.episode_id = e.id AND t.time_offset_seconds = 1800
  );
