CREATE TABLE podcast_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    thesis TEXT,
    description TEXT,
    audio_url VARCHAR(1024),
    media_link VARCHAR(1024),
    duration_seconds INT,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE podcast_timecodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id BIGINT NOT NULL,
    time_offset_seconds INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    display_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_podcast_timecodes_episode FOREIGN KEY (episode_id) REFERENCES podcast_episodes (id) ON DELETE CASCADE
);

CREATE INDEX idx_podcast_timecodes_episode_id ON podcast_timecodes(episode_id);
