-- Migration: V20261009115824162__init_schema_and_seed_data.sql
-- Description: Initialize schema for publication_schedule and articles, ensure podcast_episodes columns, and seed realistic data

CREATE TABLE IF NOT EXISTS publication_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    target_date TIMESTAMP WITH TIME ZONE NOT NULL,
    summary TEXT,
    link VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    reading_time_minutes INT NOT NULL,
    tags VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PUBLISHED',
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE podcast_episodes ADD COLUMN IF NOT EXISTS episode_number INT;
ALTER TABLE podcast_episodes ADD COLUMN IF NOT EXISTS timecodes TEXT;

-- Seed Publication Schedule
INSERT INTO publication_schedule (title, topic, platform, status, target_date, summary, link) VALUES
('Деонтическая логика в архитектуре микросервисов', 'Деонтическая логика', 'TELEGRAM', 'PUBLISHED', '2026-10-01 10:00:00+00', 'Заметка о применении операторов O (обязательно), P (разрешено), F (запрещено) в API контрактах.', 'https://t.me/efremov_mvp/101'),
('Теория ограничений (TOC) для высоконагруженных систем', 'Теория ограничений', 'YOUTUBE', 'IN_PRODUCTION', '2026-10-15 18:00:00+00', 'Разбор узких мест в распределенных базах данных и паттернов устранения заторов.', 'https://youtube.com/@efremov_dmitriy'),
('Автономные процессы и идемпотентные пайплайны', 'Автономные системы', 'ARTICLE', 'SCHEDULED', '2026-10-20 12:00:00+00', 'Лонгрид о построении самовосстанавливающихся конвейеров обработки данных.', '/articles/autonomous-processes-idempotent-pipelines');

-- Seed Podcast Episodes ("Системы и реальность")
INSERT INTO podcast_episodes (slug, episode_number, title, thesis, description, audio_url, media_link, duration_seconds, timecodes, published_at) VALUES
('ep-01-invariants', 1, 'Системы и реальность: Эпизод 01. Инварианты архитектуры', 'Почему код и архитектурные решения отражают мышление разработчика. Разбор системных инвариантов и деонтической чистоты.', 'Разбор системных инвариантов и деонтической чистоты в архитектуре.', 'https://cdn.dmitryefremov.com/podcasts/ep01.mp3', 'https://cdn.dmitryefremov.com/podcasts/ep01.mp3', 2700, '[{"time":"00:00","title":"Введение и манифест"},{"time":"08:30","title":"Инварианты и границы систем"},{"time":"22:15","title":"Деонтическая логика на практике"},{"time":"39:00","title":"Заключение"}]', '2026-09-15 12:00:00+00'),
('ep-02-toc', 2, 'Системы и реальность: Эпизод 02. Теория ограничений Голдратта', 'Как находить и устранять системные узкие места в автономных процессах и архитектурных потоках.', 'Практический разбор теории ограничений для автономных процессов.', 'https://cdn.dmitryefremov.com/podcasts/ep02.mp3', 'https://cdn.dmitryefremov.com/podcasts/ep02.mp3', 3120, '[{"time":"00:00","title":"Теория ограничений в инженерии"},{"time":"14:10","title":"Поиск главного узкого места"},{"time":"31:45","title":"Оптимизация throughput"},{"time":"48:20","title":"Вопросы и ответы"}]', '2026-09-29 12:00:00+00');

-- Seed Podcast Timecodes for Episode 1
INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 0, 'Введение и манифест', 'Вводный обзор', 1 FROM podcast_episodes WHERE slug = 'ep-01-invariants';
INSERT INTO podcast_timecodes (episode_id, time_offset_seconds, title, description, display_order)
SELECT id, 510, 'Инварианты и границы систем', 'Анализ системных границ', 2 FROM podcast_episodes WHERE slug = 'ep-01-invariants';

-- Seed Articles
INSERT INTO articles (slug, title, summary, content, reading_time_minutes, tags, status, published_at) VALUES
('deontic-logic-in-software-architecture', 'Деонтическая логика и системные инварианты', 'Исследование применения деонтических операторов для формализации требований и контроля за состоянием распределенных систем.', '# Деонтическая логика и системные инварианты

Ваш код и ваши решения — это то, кто вы есть на самом деле.

## Введение
Деонтическая логика оперирует понятиями обязательного (O), разрешенного (P) и запрещенного (F). В инженерии ПО это позволяет строго формулировать инварианты.

> Системная чистота достигается тогда, когда невалидные состояния физически невыразимы в коде.

### Формула деонтической согласованности
O(p) <=> not P(not p)
', 8, 'Logic, Architecture, Systems', 'PUBLISHED', '2026-09-20 10:00:00+00'),
('theory-of-constraints-autonomous-systems', 'Теория ограничений в автономных системах', 'Практическое руководство по идентификации и подчинению ограничений в распределенных конвейерах данных.', '# Теория ограничений в автономных системах

Каждая система имеет ровно одно главное ограничение, определяющее её пропускную способность.

1. Идентифицировать ограничение.
2. Максимально использовать ограничение.
3. Подчинить всё остальное этому решению.
4. Расшить ограничение.
5. Вернуться к шагу 1.
', 12, 'TOC, Engineering, Systems', 'PUBLISHED', '2026-09-28 14:00:00+00');
